import type { ErrorEvent } from "@sentry/cloudflare";
import { Match, Option } from "effect";

const ERROR_TYPES = new Set([
  "Error",
  "TypeError",
  "RangeError",
  "ReferenceError",
  "SyntaxError",
  "URIError",
  "AggregateError",
  "UserStoreError",
  "WorkOSError",
  "McpSessionMetaUnavailableError",
  "GateCheckTimeoutError",
  "AutumnError",
]);

const OPERATIONS = new Set([
  "ensureAccount",
  "getAccount",
  "upsertOrganization",
  "getOrganization",
  "getOrganizationBySlug",
  "markOrganizationDeleted",
  "deleteOrganizationCascade",
]);
const REASONS = new Set(["connect_timeout", "connection_closed", "query", "unknown", "upstream"]);

// A field name alone does not make its contents safe. Accept only the values
// generated by these diagnostic contracts, including exact correlation widths.
const safeTag = (key: string, value: unknown): boolean => {
  if (typeof value !== "string" && typeof value !== "number") return false;
  const text = String(value);
  return Match.value(key).pipe(
    Match.when("otel_trace_id", () => /^[0-9a-f]{32}$/.test(text)),
    Match.when("otel_span_id", () => /^[0-9a-f]{16}$/.test(text)),
    Match.when("operation", () => OPERATIONS.has(text)),
    Match.when("reason", () => REASONS.has(text)),
    Match.when("status", () => /^[1-5][0-9]{2}$/.test(text)),
    Match.when("mcp.do.cause_owner", () => text === "durable_object"),
    Match.option,
    Option.getOrElse(() => false),
  );
};

const identifier = (value: string | undefined): string | undefined =>
  value !== undefined && /^[\w.$<>:/@ -]{1,160}$/.test(value) ? value : undefined;

const sourceFile = (value: string | undefined): string | undefined => {
  if (!value) return undefined;
  const path = URL.canParse(value) ? new URL(value).pathname : value.split(/[?#]/)[0];
  return path && /^\/?(?:assets\/)?[\w./-]+\.(?:js|mjs|ts|tsx)$/.test(path) ? path : undefined;
};

/** Keep error classification, source positions and correlation; omit all raw payloads. */
export const minimizeSentryEvent = (event: ErrorEvent): ErrorEvent => ({
  type: undefined,
  event_id: event.event_id,
  timestamp: event.timestamp,
  platform: event.platform,
  level: event.level,
  release: event.release,
  environment: event.environment,
  tags: Object.fromEntries(
    Object.entries(event.tags ?? {}).filter(([key, value]) => safeTag(key, value)),
  ),
  exception: {
    values: event.exception?.values?.map((exception) => ({
      type:
        exception.type !== undefined && ERROR_TYPES.has(exception.type) ? exception.type : "Error",
      value: "Details omitted to protect request data",
      mechanism: exception.mechanism
        ? {
            type: identifier(exception.mechanism.type) ?? "generic",
            handled: exception.mechanism.handled,
          }
        : undefined,
      stacktrace: {
        frames: exception.stacktrace?.frames?.map((frame) => ({
          filename: sourceFile(frame.filename),
          function: identifier(frame.function),
          module: identifier(frame.module),
          lineno: frame.lineno,
          colno: frame.colno,
          in_app: frame.in_app,
        })),
      },
    })),
  },
});
